### ISSUE TITLE
Accept spaces between switch and options with -X and -t

### ISSUE THREAD

**Issue by mdom** [woffs/haskell-amqp-utils#4]
Or is there a reason why those two options are the only ones that require no space between switch and argument?

**Comment by woffs** [comment]
This is just how https://hackage.haskell.org/package/base-4.12.0.0/docs/System-Console-GetOpt.html works in case of `OptArg`.

- no -X -> no script call
- just -X -> default script call
- -Xscript -> call custom script

- no -t -> no temp file creation
- just -t -> tempfile in /tmp
- -t/var/tmp -> tempfile in /var/tmp
